version: "3"

services:
  frontend:
    image: op/frontend:latest
    container_name: frontend
    build: ./frontend
    volumes:
      -  op-volume:/frontend/
      - ./frontend:/frontend/
    ports:
      - 3000:3000
    working_dir: /frontend/
    stdin_open: true
    restart: always
  backend:
    image: op/backend:latest
    container_name: backend
    build: ./backend
    volumes:
      - op-volume:/backend/
      - ./backend:/backend
    ports:
      - 3001:3001
    environment:
      DB_HOST_NAME: storage
    depends_on:
      - storage
    restart: always

  storage:
    image: storage
    container_name: storage
    build: ./backend/db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always
volumes:
  op-volume:
  postgres-volume: